Repository Five-Fishes/Club-Management-Spring-Server, pull requests merged in 2021-06, with the labels that each got.

#146 Yaw issue140&141 event with image
  src/main/java/com/thirdcc/webapp/domain/Event.java
  src/main/java/com/thirdcc/webapp/service/EventService.java
  src/main/java/com/thirdcc/webapp/service/dto/EventDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/EventServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/EventResource.java
  src/main/resources/config/liquibase/changelog/20210523150936_added_column_Event.xml
  src/main/resources/config/liquibase/master.xml
  src/test/java/com/thirdcc/webapp/config/ImageStorageServiceConfiguration.java
  src/test/java/com/thirdcc/webapp/web/rest/EventResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/ImageStorageResourceIT.java
Labels: dev, event

#155 Map Image Storage Method
  src/main/java/com/thirdcc/webapp/service/impl/EventServiceImpl.java
Labels: bug, dev

#143 Luxianze/transaction api
  src/main/java/com/thirdcc/webapp/authorization/ManagementTeamSecurityExpression.java
  src/main/java/com/thirdcc/webapp/authorization/TransactionSecurityExpression.java
  src/main/java/com/thirdcc/webapp/domain/Transaction.java
  src/main/java/com/thirdcc/webapp/domain/enumeration/TransactionStatus.java
  src/main/java/com/thirdcc/webapp/service/TransactionService.java
  src/main/java/com/thirdcc/webapp/service/dto/ImageStorageDTO.java
  src/main/java/com/thirdcc/webapp/service/dto/TransactionDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/TransactionServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/ImageStorageResource.java
  src/main/java/com/thirdcc/webapp/web/rest/TransactionResource.java
  src/main/resources/config/liquibase/data/faculty_TestFaker.csv
  src/test/java/com/thirdcc/webapp/config/CacheConfiguration.java
  src/test/java/com/thirdcc/webapp/service/dto/ImageStorageDTOTest.java
  src/test/java/com/thirdcc/webapp/web/rest/FacultyResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/ImageStorageResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/TransactionResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/UserResourceIT.java
Labels: dev, enhancement, finance

#156 Yaw issue150&151
  src/main/java/com/thirdcc/webapp/service/AdministratorService.java
  src/main/java/com/thirdcc/webapp/service/dto/AdministratorDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/AdministratorServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/AdministratorResource.java
  src/main/java/com/thirdcc/webapp/web/rest/ClaimResource.java
  src/main/java/com/thirdcc/webapp/web/rest/DebtResource.java
  src/test/java/com/thirdcc/webapp/web/rest/AdministratorResourceIT.java
Labels: dev, member

#149 Finance report get statistic current year session
  src/main/java/com/thirdcc/webapp/service/FinanceReportService.java
  src/main/java/com/thirdcc/webapp/service/dto/FinanceReportStatisticDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/FinanceReportServiceImpl.java
  src/main/java/com/thirdcc/webapp/utils/YearSessionUtils.java
  src/main/java/com/thirdcc/webapp/web/rest/FinanceReportResource.java
  src/test/java/com/thirdcc/webapp/web/rest/FinanceReportResourceIT.java
Labels: dev, finance
