Repository Five-Fishes/Club-Management-Spring-Server, pull requests merged in 2021-08, with the labels that each got.

#168 Refactor tests with create CC info with preauthorise
  src/main/java/com/thirdcc/webapp/web/rest/EventResource.java
  src/main/java/com/thirdcc/webapp/web/rest/UserCCInfoResource.java
  src/test/java/com/thirdcc/webapp/web/rest/UserCCInfoResourceIT.java
Labels: dev, member

#169 yearSession value List API with pagination
  src/main/java/com/thirdcc/webapp/web/rest/YearSessionResource.java
Labels: dev

#165 Convert userCCInfo to userCCInfoDTO and vice versa
  src/main/java/com/thirdcc/webapp/domain/UserCCInfo.java
  src/main/java/com/thirdcc/webapp/service/dto/UserCCInfoDTO.java
Labels: bug
