Repository Five-Fishes/Club-Management-Spring-Server, pull requests merged in 2021-05, with the labels that each got.

#127 Yaw issue102 curent user details
  src/main/java/com/thirdcc/webapp/repository/UserCCInfoRepository.java
  src/main/java/com/thirdcc/webapp/service/UserCCInfoService.java
  src/main/java/com/thirdcc/webapp/service/UserService.java
  src/main/java/com/thirdcc/webapp/service/dto/UserCCInfoDTO.java
  src/main/java/com/thirdcc/webapp/service/dto/UserDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/UserCCInfoServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/UserResource.java
  src/main/resources/config/liquibase/changelog/20210427_load_test_faker_ClubFamily.xml
  src/main/resources/config/liquibase/data/club_family_TestFaker.csv
  src/main/resources/config/liquibase/master.xml
  src/test/java/com/thirdcc/webapp/web/rest/UserResourceIT.java
Labels: authentication, dev

#129 Dev version 1
  src/main/java/com/thirdcc/webapp/repository/EventRepository.java
  src/main/java/com/thirdcc/webapp/service/EventService.java
  src/main/java/com/thirdcc/webapp/service/impl/EventServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/EventAttendeeResource.java
  src/main/java/com/thirdcc/webapp/web/rest/EventResource.java
  src/test/java/com/thirdcc/webapp/web/rest/EventAttendeeResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/EventResourceIT.java
Labels: dev

#132 Yaw issue105
  src/main/java/com/thirdcc/webapp/domain/enumeration/CCRoleType.java
  src/main/java/com/thirdcc/webapp/repository/AdministratorRepository.java
  src/main/java/com/thirdcc/webapp/repository/EventCrewRepository.java
  src/main/java/com/thirdcc/webapp/repository/UserCCInfoRepository.java
  src/main/java/com/thirdcc/webapp/service/AdministratorService.java
  src/main/java/com/thirdcc/webapp/service/EventCrewService.java
  src/main/java/com/thirdcc/webapp/service/UserCCInfoService.java
  src/main/java/com/thirdcc/webapp/service/dto/EventCrewDTO.java
  src/main/java/com/thirdcc/webapp/service/dto/UserCCRoleDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/AdministratorServiceImpl.java
  src/main/java/com/thirdcc/webapp/service/impl/EventCrewServiceImpl.java
  src/main/java/com/thirdcc/webapp/service/impl/UserCCInfoServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/UserCCInfoResource.java
  src/test/java/com/thirdcc/webapp/web/rest/UserCCInfoResourceIT.java
Labels: authentication, dev

#130 Current Logic User CC Info
  src/main/java/com/thirdcc/webapp/repository/UserCCInfoRepository.java
  src/main/java/com/thirdcc/webapp/service/UserCCInfoService.java
  src/main/java/com/thirdcc/webapp/service/dto/UserCCInfoDTO.java
  src/main/java/com/thirdcc/webapp/service/dto/UserUniInfoDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/UserCCInfoServiceImpl.java
  src/main/java/com/thirdcc/webapp/service/impl/UserUniInfoServiceImpl.java
  src/main/java/com/thirdcc/webapp/utils/FishLevelUtils.java
  src/main/java/com/thirdcc/webapp/utils/YearSessionUtils.java
  src/main/java/com/thirdcc/webapp/web/rest/UserCCInfoResource.java
  src/test/java/com/thirdcc/webapp/utils/FishLevelUtilsTest.java
  src/test/java/com/thirdcc/webapp/utils/YearSessionUtilsTest.java
  src/test/java/com/thirdcc/webapp/web/rest/UserCCInfoResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/UserUniInfoResourceIT.java
Labels: authentication, dev

#136 Yaw profile api add on
  src/main/java/com/thirdcc/webapp/domain/ClubFamily.java
  src/main/java/com/thirdcc/webapp/service/ClubFamilyService.java
  src/main/java/com/thirdcc/webapp/service/dto/ClubFamilyDTO.java
  src/main/java/com/thirdcc/webapp/service/dto/UserUniInfoDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/ClubFamilyServiceImpl.java
  src/main/java/com/thirdcc/webapp/service/impl/UserCCInfoServiceImpl.java
  src/main/java/com/thirdcc/webapp/service/impl/UserUniInfoServiceImpl.java
  src/main/resources/config/liquibase/changelog/20210510104832_alter_column_clubFamily.xml
  src/main/resources/config/liquibase/data/club_family_TestFaker.csv
  src/main/resources/config/liquibase/master.xml
  src/test/java/com/thirdcc/webapp/web/rest/UserCCInfoResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/UserUniInfoResourceIT.java
Labels: authentication, dev

#137 [Refractor] Deprecate isProfileCompleted, use getAccountDetails instead
  src/main/java/com/thirdcc/webapp/service/dto/AccountDetailsDTO.java
  src/main/java/com/thirdcc/webapp/web/rest/AccountResource.java
  src/test/java/com/thirdcc/webapp/web/rest/AccountResourceIT.java
Labels: authentication, bug

#135 Update database
  src/main/java/com/thirdcc/webapp/config/CacheConfiguration.java
  src/main/java/com/thirdcc/webapp/domain/Claim.java
  src/main/java/com/thirdcc/webapp/domain/Debt.java
  src/main/java/com/thirdcc/webapp/domain/Transaction.java
  src/main/java/com/thirdcc/webapp/repository/ClaimRepository.java
  src/main/java/com/thirdcc/webapp/repository/DebtRepository.java
  src/main/java/com/thirdcc/webapp/repository/TransactionRepository.java
  src/main/java/com/thirdcc/webapp/service/ClaimService.java
  src/main/java/com/thirdcc/webapp/service/DebtService.java
  src/main/java/com/thirdcc/webapp/service/dto/ClaimDTO.java
  src/main/java/com/thirdcc/webapp/service/dto/DebtDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/ClaimServiceImpl.java
  src/main/java/com/thirdcc/webapp/service/impl/DebtServiceImpl.java
  src/main/java/com/thirdcc/webapp/service/impl/FinanceReportServiceImpl.java
  src/main/java/com/thirdcc/webapp/service/impl/TransactionServiceImpl.java
  src/main/java/com/thirdcc/webapp/service/mapper/ClaimMapper.java
  src/main/java/com/thirdcc/webapp/service/mapper/DebtMapper.java
  src/main/java/com/thirdcc/webapp/web/rest/ClaimResource.java
  src/main/java/com/thirdcc/webapp/web/rest/DebtResource.java
  src/main/resources/config/liquibase/changelog/20210510_transaction_table_update.xml
  src/main/resources/config/liquibase/master.xml
  src/test/java/com/thirdcc/webapp/web/rest/ClaimResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/CourseProgramResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/DebtResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/FinanceReportResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/TransactionResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/UserResourceIT.java
Labels: documentation, enhancement, finance, liquibase, task

#142 Hotfix for transaction table, title column default value issue
  .gitignore
  mvnw
  src/main/resources/config/liquibase/changelog/20210510_transaction_table_update.xml
  src/main/resources/config/liquibase/master.xml
Labels: bug, finance
