Repository Five-Fishes/Club-Management-Spring-Server, pull requests merged in 2021-03, with the labels that each got.

#51 Create and update transaction
  src/main/java/com/thirdcc/webapp/authorization/ManagementTeamSecurityExpression.java
  src/main/java/com/thirdcc/webapp/config/SecurityConfiguration.java
  src/main/java/com/thirdcc/webapp/domain/Receipt.java
  src/main/java/com/thirdcc/webapp/domain/Transaction.java
  src/main/java/com/thirdcc/webapp/domain/enumeration/TransactionStatus.java
  src/main/java/com/thirdcc/webapp/service/TransactionService.java
  src/main/java/com/thirdcc/webapp/service/dto/ReceiptDTO.java
  src/main/java/com/thirdcc/webapp/service/dto/TransactionDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/TransactionServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/TransactionResource.java
  src/main/resources/config/liquibase/changelog/20201206112523_added_column_transacation_status.xml
  src/main/resources/config/liquibase/changelog/20201206115923_added_column_receipt_receiptUniqueId.xml
  src/main/resources/config/liquibase/master.xml
  src/test/java/com/thirdcc/webapp/web/rest/TransactionResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/UserJWTControllerIT.java
  src/test/java/com/thirdcc/webapp/web/rest/UserResourceIT.java
Labels: dev, task

#75 Luxianze/update event
  src/main/java/com/thirdcc/webapp/web/rest/EventResource.java
  src/test/java/com/thirdcc/webapp/web/rest/EventResourceIT.java
Labels: dev

#79 Firebase auth
  README.md
  pom.xml
  src/main/java/com/thirdcc/webapp/config/ApplicationProperties.java
  src/main/java/com/thirdcc/webapp/config/FirebaseAppConfig.java
  src/main/java/com/thirdcc/webapp/config/SecurityConfiguration.java
  src/main/java/com/thirdcc/webapp/domain/User.java
  src/main/java/com/thirdcc/webapp/repository/UserRepository.java
  src/main/java/com/thirdcc/webapp/security/firebase/FirebaseAuthenticationToken.java
  src/main/java/com/thirdcc/webapp/security/firebase/FirebaseConstants.java
  src/main/java/com/thirdcc/webapp/security/firebase/FirebaseService.java
  src/main/java/com/thirdcc/webapp/security/firebase/FirebaseTokenHolder.java
  src/main/java/com/thirdcc/webapp/security/firebase/exception/FirebaseTokenException.java
  src/main/java/com/thirdcc/webapp/security/firebase/exception/FirebaseTokenExceptionMessages.java
  src/main/java/com/thirdcc/webapp/service/UserService.java
  src/main/java/com/thirdcc/webapp/utils/FirebaseUtils.java
  src/main/java/com/thirdcc/webapp/web/rest/UserJWTController.java
  src/main/resources/config/application.yml
  src/test/java/com/thirdcc/webapp/web/rest/UserJWTControllerIT.java
  src/test/resources/config/application.yml
Labels: authentication

#83 Refresh token
  src/main/java/com/thirdcc/webapp/config/ApplicationProperties.java
  src/main/java/com/thirdcc/webapp/config/SecurityConfiguration.java
  src/main/java/com/thirdcc/webapp/security/jwt/AccessTokenProvider.java
  src/main/java/com/thirdcc/webapp/security/jwt/JWTConfigurer.java
  src/main/java/com/thirdcc/webapp/security/jwt/JWTFilter.java
  src/main/java/com/thirdcc/webapp/security/jwt/RefreshTokenProvider.java
  src/main/java/com/thirdcc/webapp/web/rest/UserJWTController.java
  src/main/resources/config/application-dev.yml
  src/main/resources/config/application-prod.yml
  src/test/java/com/thirdcc/webapp/security/jwt/AccessTokenProviderTest.java
  src/test/java/com/thirdcc/webapp/security/jwt/JWTFilterTest.java
  src/test/java/com/thirdcc/webapp/security/jwt/RefreshTokenProviderTest.java
  src/test/java/com/thirdcc/webapp/web/rest/UserJWTControllerIT.java
  src/test/resources/config/application.yml
Labels: authentication, dev

#58 Get event attendees
  .github/workflows/maven-junit.yml
  src/main/java/com/thirdcc/webapp/repository/EventAttendeeRepository.java
  src/main/java/com/thirdcc/webapp/service/EventAttendeeService.java
  src/main/java/com/thirdcc/webapp/service/impl/EventAttendeeServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/EventAttendeeResource.java
  src/test/java/com/thirdcc/webapp/web/rest/EventAttendeeResourceIT.java
Labels: dev, task

#77 Cancel Event
  src/main/java/com/thirdcc/webapp/service/EventService.java
  src/main/java/com/thirdcc/webapp/service/impl/EventServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/EventResource.java
  src/test/java/com/thirdcc/webapp/web/rest/EventResourceIT.java
Labels: dev

#89 Fetch account
  src/main/java/com/thirdcc/webapp/repository/EventCrewRepository.java
  src/main/java/com/thirdcc/webapp/service/dto/AccountDetailsDTO.java
  src/main/java/com/thirdcc/webapp/web/rest/AccountResource.java
  src/test/java/com/thirdcc/webapp/annotations/authorization/AbstractSecurityContextFactoryTemplate.java
  src/test/java/com/thirdcc/webapp/annotations/authorization/WithCurrentCCAdministrator.java
  src/test/java/com/thirdcc/webapp/annotations/authorization/WithCurrentCCHead.java
  src/test/java/com/thirdcc/webapp/annotations/authorization/WithCustomUser.java
  src/test/java/com/thirdcc/webapp/annotations/authorization/WithEventCrew.java
  src/test/java/com/thirdcc/webapp/annotations/authorization/WithEventHead.java
  src/test/java/com/thirdcc/webapp/annotations/authorization/WithUnauthenticatedMockUser.java
  src/test/java/com/thirdcc/webapp/web/rest/AccountResourceIT.java
Labels: authentication
