Repository Five-Fishes/Club-Management-Spring-Server, pull requests merged in 2021-07, with the labels that each got.

#161 Refactored Tests for dynamic query
  src/main/java/com/thirdcc/webapp/service/UserCCInfoQueryService.java
  src/main/java/com/thirdcc/webapp/service/criteria/UserCCInfoCriteria.java
  src/main/java/com/thirdcc/webapp/service/impl/UserCCInfoServiceImpl.java
  src/main/java/com/thirdcc/webapp/service/impl/UserUniInfoServiceImpl.java
  src/test/java/com/thirdcc/webapp/web/rest/UserCCInfoResourceIT.java
Labels: dev, member

#158 Yaw issue153
  src/main/java/com/thirdcc/webapp/domain/UserCCInfo.java
  src/main/java/com/thirdcc/webapp/service/UserCCInfoQueryService.java
  src/main/java/com/thirdcc/webapp/service/criteria/UserCCInfoCriteria.java
  src/main/java/com/thirdcc/webapp/service/dto/UserCCInfoDTO.java
  src/main/java/com/thirdcc/webapp/service/mapper/UserCCInfoMapper.java
  src/main/java/com/thirdcc/webapp/web/rest/UserCCInfoResource.java
  src/test/java/com/thirdcc/webapp/web/rest/UserCCInfoResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/UserResourceIT.java
Labels: dev, member

#163 Update transaction status
  src/main/java/com/thirdcc/webapp/service/TransactionService.java
  src/main/java/com/thirdcc/webapp/service/impl/TransactionServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/TransactionResource.java
  src/test/java/com/thirdcc/webapp/web/rest/TransactionResourceIT.java
Labels: dev, finance

#166 map clubFamilyCode for UserProfile API
  src/main/java/com/thirdcc/webapp/service/dto/UserUniInfoDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/UserUniInfoServiceImpl.java
Labels: bug
