Repository Five-Fishes/Club-Management-Spring-Server, pull requests merged in 2021-04, with the labels that each got.

#59 Debt get all by event id update debt status
  src/main/java/com/thirdcc/webapp/repository/DebtRepository.java
  src/main/java/com/thirdcc/webapp/service/DebtService.java
  src/main/java/com/thirdcc/webapp/service/impl/DebtServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/DebtResource.java
  src/test/java/com/thirdcc/webapp/web/rest/DebtResourceIT.java
Labels: task

#93 Get event crew
  src/main/java/com/thirdcc/webapp/repository/EventCrewRepository.java
  src/main/java/com/thirdcc/webapp/service/EventCrewService.java
  src/main/java/com/thirdcc/webapp/service/UserService.java
  src/main/java/com/thirdcc/webapp/service/dto/EventCrewDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/EventCrewServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/EventCrewResource.java
  src/main/java/com/thirdcc/webapp/web/rest/UserResource.java
  src/test/java/com/thirdcc/webapp/web/rest/EventCrewResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/UserResourceIT.java
Labels: dev

#95 Image Upload with Firebase
  pom.xml
  src/main/java/com/thirdcc/webapp/lib/wrapper/CloudStorage.java
  src/main/java/com/thirdcc/webapp/lib/wrapper/GCPCloudStorage.java
  src/main/java/com/thirdcc/webapp/service/ImageStorageService.java
  src/main/java/com/thirdcc/webapp/service/impl/ImageStorageServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/ImageStorageResource.java
  src/test/java/com/thirdcc/webapp/web/rest/ImageStorageResourceIT.java
Labels: dev

#98 Claim get all open and update status
  src/main/java/com/thirdcc/webapp/repository/ClaimRepository.java
  src/main/java/com/thirdcc/webapp/service/ClaimService.java
  src/main/java/com/thirdcc/webapp/service/impl/ClaimServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/ClaimResource.java
  src/test/java/com/thirdcc/webapp/web/rest/ClaimResourceIT.java
Labels: dev

#97 Event attendee with year session, user name and contact number
  src/main/java/com/thirdcc/webapp/repository/EventAttendeeRepository.java
  src/main/java/com/thirdcc/webapp/repository/UserUniInfoRepository.java
  src/main/java/com/thirdcc/webapp/service/EventAttendeeService.java
  src/main/java/com/thirdcc/webapp/service/dto/EventAttendeeDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/EventAttendeeServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/EventAttendeeResource.java
  src/test/java/com/thirdcc/webapp/web/rest/EventAttendeeResourceIT.java
Labels: dev

#101 Register as Event Attendee
  src/main/java/com/thirdcc/webapp/service/EventAttendeeService.java
  src/main/java/com/thirdcc/webapp/service/impl/EventAttendeeServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/EventAttendeeResource.java
  src/test/java/com/thirdcc/webapp/web/rest/EventAttendeeResourceIT.java
Labels: dev

#106 Modified event checklist update to allow update status
  src/main/java/com/thirdcc/webapp/service/impl/EventChecklistServiceImpl.java
  src/test/java/com/thirdcc/webapp/web/rest/EventChecklistResourceIT.java
Labels: enhancement

#55 Generate event registration closing criteria
  .jhipster/EventRegistrationClosingCriteria.json
  3rc_club_management-server-jdl.jh
  src/main/java/com/thirdcc/webapp/config/CacheConfiguration.java
  src/main/java/com/thirdcc/webapp/domain/EventRegistrationClosingCriteria.java
  src/main/java/com/thirdcc/webapp/repository/EventRegistrationClosingCriteriaRepository.java
  src/main/java/com/thirdcc/webapp/service/EventRegistrationClosingCriteriaService.java
  src/main/java/com/thirdcc/webapp/service/dto/EventRegistrationClosingCriteriaDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/EventRegistrationClosingCriteriaServiceImpl.java
  src/main/java/com/thirdcc/webapp/service/mapper/EventRegistrationClosingCriteriaMapper.java
  src/main/java/com/thirdcc/webapp/web/rest/EventRegistrationClosingCriteriaResource.java
  src/main/resources/config/liquibase/changelog/20201206135020_added_entity_EventRegistrationClosingCriteria.xml
  src/main/resources/config/liquibase/data/event_registration_closing_criteria.csv
  src/main/resources/config/liquibase/master.xml
  src/test/java/com/thirdcc/webapp/web/rest/EventRegistrationClosingCriteriaResourceIT.java
Labels: dev

#110 Complete profile
  src/main/java/com/thirdcc/webapp/domain/CourseProgram.java
  src/main/java/com/thirdcc/webapp/domain/User.java
  src/main/java/com/thirdcc/webapp/domain/UserUniInfo.java
  src/main/java/com/thirdcc/webapp/domain/enumeration/Gender.java
  src/main/java/com/thirdcc/webapp/repository/CourseProgramRepository.java
  src/main/java/com/thirdcc/webapp/security/DomainUserDetailsService.java
  src/main/java/com/thirdcc/webapp/service/UserService.java
  src/main/java/com/thirdcc/webapp/service/UserUniInfoService.java
  src/main/java/com/thirdcc/webapp/service/dto/UserDTO.java
  src/main/java/com/thirdcc/webapp/service/dto/UserUniInfoDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/UserUniInfoServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/AccountResource.java
  src/main/java/com/thirdcc/webapp/web/rest/UserResource.java
  src/main/resources/config/liquibase/changelog/20210413_added_columns_User.xml
  src/main/resources/config/liquibase/changelog/20210413_added_entity_CourseProgram.xml
  src/main/resources/config/liquibase/changelog/20210413_alter_columns_UserUniInfo.xml
  src/main/resources/config/liquibase/changelog/20210416_load_test_faker_CourseProgram.xml
  src/main/resources/config/liquibase/changelog/20210416_load_test_faker_Faculty.xml
  src/main/resources/config/liquibase/data/course_program.csv
  src/main/resources/config/liquibase/data/faculty.csv
  src/main/resources/config/liquibase/master.xml
  src/test/java/com/thirdcc/webapp/annotations/authorization/WithCustomUser.java
  src/test/java/com/thirdcc/webapp/annotations/authorization/WithNormalUser.java
  src/test/java/com/thirdcc/webapp/annotations/cleanup/CleanUpNormalUser.java
  src/test/java/com/thirdcc/webapp/web/rest/AccountResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/EventAttendeeResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/UserResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/UserUniInfoResourceIT.java
  src/test/resources/config/application.yml
Labels: dev

#111 Resolve Liquibase Checksum for Faculty CSV
  src/main/resources/config/liquibase/changelog/20210416_load_test_faker_Faculty.xml
  src/main/resources/config/liquibase/data/faculty.csv
  src/main/resources/config/liquibase/data/faculty_TestFaker.csv
Labels: bug, dev

#122 Luxianze/api bug fix
  src/main/java/com/thirdcc/webapp/service/impl/EventServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/EventAttendeeResource.java
  src/test/java/com/thirdcc/webapp/web/rest/EventAttendeeResourceIT.java
Labels: bug, event

#119 getAllUpcomingEvents and getAllPastEvents
  src/main/java/com/thirdcc/webapp/repository/EventRepository.java
  src/main/java/com/thirdcc/webapp/service/EventService.java
  src/main/java/com/thirdcc/webapp/service/impl/EventServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/EventAttendeeResource.java
  src/main/java/com/thirdcc/webapp/web/rest/EventResource.java
  src/test/java/com/thirdcc/webapp/web/rest/EventAttendeeResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/EventResourceIT.java
Labels: enhancement, event

#115 Yaw issue112 course program by faculty
  src/main/java/com/thirdcc/webapp/repository/CourseProgramRepository.java
  src/main/java/com/thirdcc/webapp/service/CourseProgramService.java
  src/main/java/com/thirdcc/webapp/service/UserService.java
  src/main/java/com/thirdcc/webapp/service/UserUniInfoService.java
  src/main/java/com/thirdcc/webapp/service/dto/UserUniInfoDTO.java
  src/main/java/com/thirdcc/webapp/service/impl/CourseProgramServiceImpl.java
  src/main/java/com/thirdcc/webapp/service/impl/UserUniInfoServiceImpl.java
  src/main/java/com/thirdcc/webapp/web/rest/CourseProgramResource.java
  src/main/java/com/thirdcc/webapp/web/rest/UserUniInfoResource.java
  src/test/java/com/thirdcc/webapp/web/rest/CourseProgramResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/UserUniInfoResourceIT.java
Labels: academic, dev

#126 Fixed getAllPastEvents business logic
  src/main/java/com/thirdcc/webapp/repository/EventRepository.java
  src/main/java/com/thirdcc/webapp/service/impl/EventServiceImpl.java
  src/test/java/com/thirdcc/webapp/web/rest/EventResourceIT.java
Labels: bug, event

#125 fix 2nd time Complete Profile cause Multiple User Uni Info Record
  src/main/java/com/thirdcc/webapp/service/impl/UserUniInfoServiceImpl.java
  src/test/java/com/thirdcc/webapp/web/rest/AccountResourceIT.java
  src/test/java/com/thirdcc/webapp/web/rest/UserUniInfoResourceIT.java
Labels: authentication, bug
